const state={agents:[],pipelines:[],skills:[],market:null};
const titles={overview:"系统概览",agents:"Agent 管理",pipelines:"工作流管理",skills:"技能市场"};
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function notice(message,error=false){const el=$("#notice");el.textContent=message;el.className=`notice${error?" error":""}`;setTimeout(()=>el.classList.add("hidden"),3500)}
async function load(){const data=await api("/api/overview");state.agents=data.agents;state.pipelines=data.pipelines;state.skills=data.skills;renderAll()}
function renderAll(){renderOverview();renderAgents();renderPipelines();renderSkills()}
function renderOverview(){const enabledAgents=state.agents.filter(a=>a.enabled).length;const activeSkills=state.skills.filter(s=>s.enabled&&!s.globally_blocked).length;$("#overview").innerHTML=`<div class="stats"><div class="stat"><strong>${enabledAgents}</strong><span>启用 Agent</span></div><div class="stat"><strong>${state.pipelines.length}</strong><span>工作流</span></div><div class="stat"><strong>${activeSkills}</strong><span>可用外部 Skill</span></div></div><div class="panel"><h2>默认工作流</h2>${pipelineSummary(state.pipelines[0])}</div>`}
function pipelineSummary(p){if(!p)return"<p>尚未创建工作流。</p>";return`<p><strong>${escapeHtml(p.name)}</strong> · 入口 ${escapeHtml(p.entry_agent)} · ${p.edges.length} 条交接边</p><div class="tags">${p.edges.slice(0,8).map(e=>`<span class="tag">${escapeHtml(e.source)} → ${escapeHtml(e.target)} · ${escapeHtml(e.condition)}</span>`).join("")}</div>`}
function allSkillNames(){return [...new Set(["conversation","task-routing","python-teaching","current-time","knowledge-retrieval","drawio-skill","skill-management","identity-management","general-answer","answer-validation",...state.skills.map(s=>s.name)])].sort()}
function renderAgents(){$("#agents").innerHTML=`<div class="toolbar"><input id="agent-filter" placeholder="搜索 Agent"><button class="primary" id="new-agent">添加 Agent</button></div><div class="grid" id="agent-grid">${state.agents.map(agentCard).join("")}</div>`;$("#new-agent").onclick=()=>openAgent();$("#agent-filter").oninput=e=>{const q=e.target.value.toLowerCase();$("#agent-grid").innerHTML=state.agents.filter(a=>(a.name+a.id+a.role).toLowerCase().includes(q)).map(agentCard).join("");bindAgentActions()};bindAgentActions()}
function agentCard(a){return`<article class="card"><div class="card-head"><h3>${escapeHtml(a.name)}</h3><span class="tag">${a.enabled?"启用":"停用"}</span></div><p>${escapeHtml(a.role||"未设置职责")}</p><div class="tags">${(a.skills||[]).map(s=>`<span class="tag">${escapeHtml(s)}</span>`).join("")||'<span class="tag">无 Skill</span>'}</div><div class="actions"><button class="secondary edit-agent" data-id="${escapeHtml(a.id)}">编辑</button><button class="danger delete-agent" data-id="${escapeHtml(a.id)}">删除</button></div></article>`}
function bindAgentActions(){document.querySelectorAll(".edit-agent").forEach(b=>b.onclick=()=>openAgent(state.agents.find(a=>a.id===b.dataset.id)));document.querySelectorAll(".delete-agent").forEach(b=>b.onclick=async()=>{if(!confirm("删除 Agent？相关工作流边需要你手动调整。"))return;await api(`/api/agents/${b.dataset.id}`,{method:"DELETE"});notice("Agent 已删除");await load()})}
function openAgent(a={id:"",name:"",role:"",persona:"",skills:[],enabled:true}){const form=$("#agent-form");form.innerHTML=`<h2>${a.id?"编辑":"添加"} Agent</h2><div class="form-grid"><label>Agent ID<input name="id" value="${escapeHtml(a.id)}" ${a.id?"readonly":""}></label><label>显示名称<input name="name" value="${escapeHtml(a.name)}"></label><label class="full">职责<input name="role" value="${escapeHtml(a.role)}"></label><label class="full">人格设定<textarea name="persona">${escapeHtml(a.persona)}</textarea></label><label class="full">Skill 绑定<select name="skills" multiple size="8">${allSkillNames().map(s=>`<option ${a.skills.includes(s)?"selected":""}>${escapeHtml(s)}</option>`).join("")}</select></label><label><input type="checkbox" name="enabled" ${a.enabled?"checked":""}> 启用 Agent</label></div><div class="actions"><button type="button" class="primary" id="save-agent">保存</button><button type="button" class="secondary" onclick="this.closest('dialog').close()">取消</button></div>`;$("#save-agent").onclick=async()=>{const fd=new FormData(form);const payload={id:fd.get("id"),name:fd.get("name"),role:fd.get("role"),persona:fd.get("persona"),enabled:fd.get("enabled")==="on",skills:[...form.elements.skills.selectedOptions].map(o=>o.value)};await api("/api/agents",{method:"POST",body:JSON.stringify(payload)});$("#agent-dialog").close();notice("Agent 已保存");await load()};$("#agent-dialog").showModal()}
function renderPipelines(){$("#pipelines").innerHTML=`<div class="toolbar"><div></div><button class="primary" id="new-pipeline">添加工作流</button></div><div class="grid">${state.pipelines.map(p=>`<article class="card"><div class="card-head"><h3>${escapeHtml(p.name)}</h3><span class="tag">${p.enabled?"启用":"停用"}</span></div>${pipelineSummary(p)}<div class="actions"><button class="secondary edit-pipeline" data-id="${p.id}">编辑</button><button class="danger delete-pipeline" data-id="${p.id}">删除</button></div></article>`).join("")}</div>`;$("#new-pipeline").onclick=()=>openPipeline();document.querySelectorAll(".edit-pipeline").forEach(b=>b.onclick=()=>openPipeline(state.pipelines.find(p=>p.id===b.dataset.id)));document.querySelectorAll(".delete-pipeline").forEach(b=>b.onclick=async()=>{if(!confirm("删除工作流？"))return;await api(`/api/pipelines/${b.dataset.id}`,{method:"DELETE"});notice("工作流已删除");await load()})}
function agentOptions(selected){return state.agents.map(a=>`<option value="${a.id}" ${a.id===selected?"selected":""}>${escapeHtml(a.name)} (${a.id})</option>`).join("")}
function edgeRow(e={source:"",target:"",condition:"always"}){return`<div class="edge-row"><select class="edge-source">${agentOptions(e.source)}</select><select class="edge-target">${agentOptions(e.target)}</select><input class="edge-condition" value="${escapeHtml(e.condition)}" placeholder="条件"><button type="button" class="danger remove-edge">×</button></div>`}
function openPipeline(p={id:"",name:"",entry_agent:state.agents[0]?.id||"",enabled:true,edges:[]}){const form=$("#pipeline-form");form.innerHTML=`<h2>${p.id?"编辑":"添加"}工作流</h2><div class="form-grid"><label>ID<input name="id" value="${escapeHtml(p.id)}" ${p.id?"readonly":""}></label><label>名称<input name="name" value="${escapeHtml(p.name)}"></label><label>入口 Agent<select name="entry_agent">${agentOptions(p.entry_agent)}</select></label><label><input type="checkbox" name="enabled" ${p.enabled?"checked":""}> 启用</label><div class="full"><div class="toolbar"><strong>交接关系</strong><button type="button" class="secondary" id="add-edge">添加边</button></div><div id="edges">${p.edges.map(edgeRow).join("")}</div></div></div><div class="actions"><button type="button" class="primary" id="save-pipeline">保存</button><button type="button" class="secondary" onclick="this.closest('dialog').close()">取消</button></div>`;const bindRemove=()=>document.querySelectorAll(".remove-edge").forEach(b=>b.onclick=()=>b.parentElement.remove());bindRemove();$("#add-edge").onclick=()=>{$("#edges").insertAdjacentHTML("beforeend",edgeRow());bindRemove()};$("#save-pipeline").onclick=async()=>{const fd=new FormData(form);const edges=[...form.querySelectorAll(".edge-row")].map(r=>({source:r.querySelector(".edge-source").value,target:r.querySelector(".edge-target").value,condition:r.querySelector(".edge-condition").value||"always"}));await api("/api/pipelines",{method:"POST",body:JSON.stringify({id:fd.get("id"),name:fd.get("name"),entry_agent:fd.get("entry_agent"),enabled:fd.get("enabled")==="on",edges})});$("#pipeline-dialog").close();notice("工作流已保存");await load()};$("#pipeline-dialog").showModal()}
function renderSkills(){$("#skills").innerHTML=`<div class="toolbar"><input id="market-query" placeholder="搜索 SkillsMP / ClawHub"><button class="primary" id="market-search">搜索市场</button></div><div id="market-results"></div><div class="panel"><h2>已安装 Skill</h2><div class="grid">${state.skills.map(skillCard).join("")||"<p>尚未安装外部 Skill。</p>"}</div></div>`;$("#market-search").onclick=searchMarket;bindSkillActions()}
function skillCard(s){return`<article class="card"><div class="card-head"><h3>${escapeHtml(s.name)}</h3><span class="tag ${s.globally_blocked?"blocked":""}">${s.globally_blocked?"全局封印":s.enabled?"已启用":"未启用"}</span></div><p>${escapeHtml(s.resolved_source||s.source)}</p><div class="actions"><button class="secondary toggle-skill" data-name="${s.name}" data-enabled="${!s.enabled}">${s.enabled?"禁用":"启用"}</button><button class="danger block-skill" data-name="${s.name}" data-blocked="${!s.globally_blocked}">${s.globally_blocked?"解除封印":"全局封印"}</button></div></article>`}
function bindSkillActions(){document.querySelectorAll(".toggle-skill").forEach(b=>b.onclick=async()=>{await api("/api/skills/enabled",{method:"POST",body:JSON.stringify({name:b.dataset.name,enabled:b.dataset.enabled==="true"})});notice("Skill 状态已更新");await load()});document.querySelectorAll(".block-skill").forEach(b=>b.onclick=async()=>{await api("/api/skills/block",{method:"POST",body:JSON.stringify({name:b.dataset.name,blocked:b.dataset.blocked==="true"})});notice("全局封印状态已更新");await load()})}
async function searchMarket(){const q=$("#market-query").value;state.market=await api(`/api/skills/search?q=${encodeURIComponent(q)}`);$("#market-results").innerHTML=`<div class="market-links"><a target="_blank" href="${state.market.external_search.skillsmp}">在 SkillsMP 查看更多</a><a target="_blank" href="${state.market.external_search.clawhub}">在 ClawHub 查看更多</a></div><div class="grid">${state.market.results.map(r=>`<article class="card"><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.description)}</p><span class="tag">${escapeHtml(r.source)}</span><div class="actions"><button class="primary install-skill" data-url="${escapeHtml(r.url)}">下载安装</button></div></article>`).join("")||"<p>本地审核目录没有匹配项，请使用上方市场链接搜索。</p>"}</div>`;document.querySelectorAll(".install-skill").forEach(b=>b.onclick=async()=>{if(!confirm("下载第三方 Skill？安装后默认不启用。"))return;await api("/api/skills/install",{method:"POST",body:JSON.stringify({source_url:b.dataset.url})});notice("Skill 已安装，默认未启用");await load()})}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-item,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`#${b.dataset.view}`).classList.add("active");$("#page-title").textContent=titles[b.dataset.view]});$("#refresh").onclick=()=>load().then(()=>notice("已刷新")).catch(e=>notice(e.message,true));load().catch(e=>notice(e.message,true));
